### ISSUE TITLE
Cannot delete a directory if it WAS a 'workspace deploy location'

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#250] opened 2023-11-03 18:43 UTC
Set an IFS directory to be the `Workspace Deploy Location` via the IFS Browser
<img width="390" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/11184579/6e6392b7-9631-4183-9572-c440880af467">
<img width="369" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/695cfad7-85cd-4163-a065-0a32afad332f">

Deploy to the directory
<img width="1044" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/d16d0030-5678-44e9-9be9-10e482599406">

If there was no Project Explorere (no `iproj.json` in the directory) then you cannot delete the project while it is a deploy directory, but it can be deleted afterwards.
But in this case it is an i pojrect 

Switch deploy to location to any other directory
![image](https://github.com/codefori/vscode-ibmi/assets/11184579/11800c74-f744-4d46-a1a7-cfcd7cb520e0)
<img width="1044" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/9d67d3e1-4752-4c6d-8d9b-3570827e78fa">

Now try to delete the original directory
![image](https://github.com/codefori/vscode-ibmi/assets/11184579/b541fa12-3f19-4163-ab7d-ed4c436c0b1d)

This delete fails
<img width="585" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/9e54b3f9-e6f2-4f7c-add2-597b9afbc6ca">

@SanjulaGanepola 
Is there some kind of file watcher that the Project Explorer sets up that needs to be deactivated?

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.83.1|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.5.1
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
Git Project Manager (git-project-manager): 1.8.2
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.4.1
IBM i Developer (ibmideveloper): 2.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.4
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5892
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
Test Adapter Converter (test-adapter-converter): 0.1.8
Test Explorer UI (vscode-test-explorer): 2.21.1
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
undefined (vscode-sourceorbit): 1.1.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
HOME=/home/reinhard/builds/ibmi-company_system
HOST=p9adt01.rch.stglabs.ibm.com
IBMIMAKE=/Build/Bob/IBMiMake
LIBLS=QTEMP QGPL TESTTOOLS
LOGIN=reinhard
LOGNAME=reinhard
MAIL=/var/spool/mail/reinhard
OBJLIB=BOBTOOLS
OLDPWD=/home/reinhard
PASE_SYSCALL_NOSIGILL=ALL:quotactl=EPERM:audit=0
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/reinhard/builds/ibmi-company_system
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=9.67.9.208 49832 22
SSH_CONNECTION=9.67.9.208 49832 9.5.160.189 22
TERM=xterm
TZ=<UTC>0
USER=reinhard
USERNAME=reinhard
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/reinhard"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/reinhard"
  },
  {
    "command": "rm -rf /home/reinhard/builds/ibmi-company_system",
    "code": 1,
    "stderr": "rm: cannot remove '/home/reinhard/builds/ibmi-company_system': Device busy",
    "cwd": "/home/reinhard/builds/ibmi-company_system"
  }
]
```
</details>

**Comment by SanjulaGanepola** [comment] 2023-11-05 17:55
@edmundreinhardt There shouldn't be any file watcher that needs to be deactivated. I tried out what you outlined and it looks like it can even be reproduced in just Code4i by simply doing the following:

1. Create a new directory.
2. Use `Set Deploy Workspace Location` on this new directory in the IFS Browser.
3. Deploy the project to this location.
4. Try to delete the directory using the IFS Browser and you will get the error "Device busy".

When testing, I did notice that this only happens when there is a `.bashrc` file. When I didn't have one, it would give the error: "Cannot remove the current directory".

My `.bashrc` content:
> export PATH="/QOpenSys/pkgs/bin:${PATH}"

**Comment by sebjulliand** [comment] 2023-11-05 18:16
Hey guys, I looked at the code in Code for i and rerproduced the issue as well.
However, it's not related to .bashrc, in my opinion. Why the deletion fails is simple: when deploying, the deploy location becomes the new current directory then the deployment commands and run. After that, trying to delete the deployment directory fails because you're basically trying to cut the branch you're seating on 😅

When running a command, we can see the current directory on the left side:
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11096890/f42a52a0-f781-4ddc-b490-5627a046b062)

I'll make a note to handle this case in Code for i. In the case the user deletes the current deploy location, we'll make `~` the new current directory.

**Comment by edmundreinhardt** [comment] 2023-11-06 09:49
Yes, Seb, I noticed that this was reproducible in Code 4 i.  But I could understand at some level, that the directory was still in use.  The unique issue to Project Explorer is that even after changing the deploy directory, the old directory cannot be deleted.

**Comment by sebjulliand** [comment] 2023-11-06 09:51
@edmundreinhardt did you try do deploy again after changing the deploy dir and before trying to delete the old one?

**Comment by edmundreinhardt** [comment] 2023-11-06 11:42
Yes, you are right.  I will close this issue here, since this is a Code 4 i issue
@sebjulliand should I open defect in code 4 i  or do you already have something there?

**Comment by sebjulliand** [comment] 2023-11-06 12:21
> Yes, you are right. I will close this issue here, since this is a Code 4 i issue @sebjulliand should I open defect in code 4 i or do you already have something there?

Please do, I don't have anything there yet. You can assign it to me right away.

**Closed** 2023-11-06 14:53 UTC
Labels: bug
